/**
 * Canonical OSIS book-id list, ordered. Useful for:
 * - resolving ordinal order when an importer doesn't provide it
 * - a fallback Table-of-Contents when the DB has no `books` rows yet
 */
export const OSIS_BOOKS: ReadonlyArray<{ osis: string; name: string; ordinal: number }> = [
  { osis: 'Gen', name: 'Genesis', ordinal: 1 },
  { osis: 'Exod', name: 'Exodus', ordinal: 2 },
  { osis: 'Lev', name: 'Leviticus', ordinal: 3 },
  { osis: 'Num', name: 'Numbers', ordinal: 4 },
  { osis: 'Deut', name: 'Deuteronomy', ordinal: 5 },
  { osis: 'Josh', name: 'Joshua', ordinal: 6 },
  { osis: 'Judg', name: 'Judges', ordinal: 7 },
  { osis: 'Ruth', name: 'Ruth', ordinal: 8 },
  { osis: '1Sam', name: '1 Samuel', ordinal: 9 },
  { osis: '2Sam', name: '2 Samuel', ordinal: 10 },
  { osis: '1Kgs', name: '1 Kings', ordinal: 11 },
  { osis: '2Kgs', name: '2 Kings', ordinal: 12 },
  { osis: '1Chr', name: '1 Chronicles', ordinal: 13 },
  { osis: '2Chr', name: '2 Chronicles', ordinal: 14 },
  { osis: 'Ezra', name: 'Ezra', ordinal: 15 },
  { osis: 'Neh', name: 'Nehemiah', ordinal: 16 },
  { osis: 'Esth', name: 'Esther', ordinal: 17 },
  { osis: 'Job', name: 'Job', ordinal: 18 },
  { osis: 'Ps', name: 'Psalms', ordinal: 19 },
  { osis: 'Prov', name: 'Proverbs', ordinal: 20 },
  { osis: 'Eccl', name: 'Ecclesiastes', ordinal: 21 },
  { osis: 'Song', name: 'Song of Solomon', ordinal: 22 },
  { osis: 'Isa', name: 'Isaiah', ordinal: 23 },
  { osis: 'Jer', name: 'Jeremiah', ordinal: 24 },
  { osis: 'Lam', name: 'Lamentations', ordinal: 25 },
  { osis: 'Ezek', name: 'Ezekiel', ordinal: 26 },
  { osis: 'Dan', name: 'Daniel', ordinal: 27 },
  { osis: 'Hos', name: 'Hosea', ordinal: 28 },
  { osis: 'Joel', name: 'Joel', ordinal: 29 },
  { osis: 'Amos', name: 'Amos', ordinal: 30 },
  { osis: 'Obad', name: 'Obadiah', ordinal: 31 },
  { osis: 'Jonah', name: 'Jonah', ordinal: 32 },
  { osis: 'Mic', name: 'Micah', ordinal: 33 },
  { osis: 'Nah', name: 'Nahum', ordinal: 34 },
  { osis: 'Hab', name: 'Habakkuk', ordinal: 35 },
  { osis: 'Zeph', name: 'Zephaniah', ordinal: 36 },
  { osis: 'Hag', name: 'Haggai', ordinal: 37 },
  { osis: 'Zech', name: 'Zechariah', ordinal: 38 },
  { osis: 'Mal', name: 'Malachi', ordinal: 39 },
  { osis: 'Matt', name: 'Matthew', ordinal: 40 },
  { osis: 'Mark', name: 'Mark', ordinal: 41 },
  { osis: 'Luke', name: 'Luke', ordinal: 42 },
  { osis: 'John', name: 'John', ordinal: 43 },
  { osis: 'Acts', name: 'Acts', ordinal: 44 },
  { osis: 'Rom', name: 'Romans', ordinal: 45 },
  { osis: '1Cor', name: '1 Corinthians', ordinal: 46 },
  { osis: '2Cor', name: '2 Corinthians', ordinal: 47 },
  { osis: 'Gal', name: 'Galatians', ordinal: 48 },
  { osis: 'Eph', name: 'Ephesians', ordinal: 49 },
  { osis: 'Phil', name: 'Philippians', ordinal: 50 },
  { osis: 'Col', name: 'Colossians', ordinal: 51 },
  { osis: '1Thess', name: '1 Thessalonians', ordinal: 52 },
  { osis: '2Thess', name: '2 Thessalonians', ordinal: 53 },
  { osis: '1Tim', name: '1 Timothy', ordinal: 54 },
  { osis: '2Tim', name: '2 Timothy', ordinal: 55 },
  { osis: 'Titus', name: 'Titus', ordinal: 56 },
  { osis: 'Phlm', name: 'Philemon', ordinal: 57 },
  { osis: 'Heb', name: 'Hebrews', ordinal: 58 },
  { osis: 'Jas', name: 'James', ordinal: 59 },
  { osis: '1Pet', name: '1 Peter', ordinal: 60 },
  { osis: '2Pet', name: '2 Peter', ordinal: 61 },
  { osis: '1John', name: '1 John', ordinal: 62 },
  { osis: '2John', name: '2 John', ordinal: 63 },
  { osis: '3John', name: '3 John', ordinal: 64 },
  { osis: 'Jude', name: 'Jude', ordinal: 65 },
  { osis: 'Rev', name: 'Revelation', ordinal: 66 },
];

export function osisNameFor(osisId: string): string {
  return OSIS_BOOKS.find((b) => b.osis.toLowerCase() === osisId.toLowerCase())?.name ?? osisId;
}
